# Nix home-manager configuration example for mailjail
#
# Add this to your home-manager configuration to set up mailjail as a
# systemd user service with automatic startup and management.
#
# Usage: Include this in your home-manager configuration and adjust
# the paths and settings to match your setup.

{ config, pkgs, lib, ... }:

let
  mailjailSrc = pkgs.fetchGit {
    url = "https://github.com/akaihola/mailjail";
    rev = "main";  # Pin to a specific revision for reproducibility
  };

  mailjailPackage = pkgs.python3.pkgs.callPackage "${mailjailSrc}/pyproject.toml" {
    cryptography = pkgs.python3.pkgs.cryptography;  # Required for Thunderbird support
  };

in {
  # Home-manager configuration for mailjail
  home = {
    packages = [ mailjailPackage ];
  };

  # Systemd user service
  systemd.user.services.mailjail = {
    Unit = {
      Description = "mailjail — JMAP-shaped read-only IMAP proxy";
      Documentation = "file://${config.home.homeDirectory}/.config/mailjail/README.md";
      After = [ "network.target" ];
    };

    Service = {
      Type = "simple";
      ExecStart = "${mailjailPackage}/bin/python -m mailjail";
      Restart = "on-failure";
      RestartSec = 10;

      # Security hardening
      PrivateTmp = true;
      NoNewPrivileges = true;
      ProtectSystem = "strict";
      ProtectHome = true;
      ReadWritePaths = [
        "${config.home.homeDirectory}/.config/mailjail"
        "${config.home.homeDirectory}/.cache/mailjail"
        "${config.home.homeDirectory}/.thunderbird"
      ];

      # Resource limits
      MemoryMax = "256M";
      CPUQuota = "50%";

      # Environment variables (optional)
      Environment = [
        "PYTHONUNBUFFERED=1"
      ];
    };

    Install = {
      WantedBy = [ "default.target" ];
    };

    # Start the service on login
    wants = [ "default.target" ];
  };

  # Socket activation (optional - for better integration)
  systemd.user.sockets.mailjail = {
    Unit = {
      Description = "mailjail JMAP HTTP socket";
      PartOf = [ "mailjail.service" ];
    };

    Socket = {
      ListenStream = "127.0.0.1:8895";
      Accept = false;
    };

    Install = {
      WantedBy = [ "sockets.target" ];
    };
  };

  # Configuration file management
  home.file.".config/mailjail/config.toml" = {
    text = ''
      # mailjail configuration
      # Generated by home-manager

      primary_account = "personal"

      [server]
      host = "127.0.0.1"
      port = 8895

      [accounts.personal]
      host = "imap.example.com"
      port = 993
      ssl = true
      username = "user@example.com"
      drafts_folder = "Drafts"

      [accounts.personal.auth]
      provider = "thunderbird"
      thunderbird_dir = "${config.home.homeDirectory}/.thunderbird"
      thunderbird_profile = "default"

      [accounts.personal.pool]
      size = 3
    '';
    onChange = "${pkgs.systemd}/bin/systemctl --user restart mailjail.service";
  };

  # Optional: Shell alias for convenient testing
  programs.bash.shellAliases = {
    mailjail-status = "systemctl --user status mailjail.service";
    mailjail-logs = "journalctl --user -u mailjail.service -f";
    mailjail-test = "curl -s http://127.0.0.1:8895/.well-known/jmap | ${pkgs.jq}/bin/jq .";
  };

  # Optional: Create a script to manage mailjail
  home.file.".local/bin/mailjail-ctl" = {
    executable = true;
    text = ''
      #!/usr/bin/env bash
      set -euo pipefail

      case "''${1:-status}" in
        start)
          systemctl --user start mailjail.service
          echo "mailjail started"
          ;;
        stop)
          systemctl --user stop mailjail.service
          echo "mailjail stopped"
          ;;
        restart)
          systemctl --user restart mailjail.service
          echo "mailjail restarted"
          ;;
        status)
          systemctl --user status mailjail.service
          ;;
        logs)
          journalctl --user -u mailjail.service -f
          ;;
        health)
          echo "Checking mailjail health..."
          ${pkgs.curl}/bin/curl -s http://127.0.0.1:8895/healthz | ${pkgs.jq}/bin/jq .
          ;;
        *)
          cat <<EOF
      Usage: mailjail-ctl {start|stop|restart|status|logs|health}

      Commands:
        start   - Start the mailjail service
        stop    - Stop the mailjail service
        restart - Restart the mailjail service
        status  - Show service status
        logs    - Follow service logs
        health  - Check IMAP connection health
      EOF
          exit 1
          ;;
      esac
    '';
  };
}
